# Generated by Django 2.2 on 2020-08-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_pic',
            field=models.ImageField(blank=True, default='dishes/blank-dish.jpg', null=True, upload_to='course_directory_path'),
        ),
    ]
