# Generated by Django 3.0.8 on 2020-09-01 01:17

import dish.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_auto_20200830_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='profile_pic',
            field=models.ImageField(blank=True, default='dishes/blank-dish.jpg', null=True, upload_to=dish.models.dish_directory_path),
        ),
        migrations.AlterField(
            model_name='rating',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=dish.models.dish_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/blank-user.jpg', null=True, upload_to=dish.models.user_directory_path),
        ),
    ]
