# Generated by Django 3.0.8 on 2020-09-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_auto_20200901_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(),
        ),
    ]
