# Generated by Django 2.2 on 2020-09-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0005_auto_20200901_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
