# Generated by Django 2.2 on 2020-09-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0006_category_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='profile_pic',
            field=models.ImageField(blank=True, default='categories/blank-dish.jpg', null=True, upload_to='categories/'),
        ),
    ]
