# Generated by Django 2.2 on 2020-09-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0007_auto_20200901_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='profile_pic',
            field=models.ImageField(blank=True, default='categories/blank-category.jpg', null=True, upload_to='categories/'),
        ),
    ]
